spring:
  application:
    name: real-time-collaborative-doc
  data:
    redis:
      host: localhost
      port: 6379
      password: ${password:20050603RJ}
      database: 4
            # password: 你的密码（如果有）
            # database: 0  # 默认 0
  mongodb:
    uri: mongodb+srv://ranjin:${password:123456789%21}@attached.vpgh8cz.mongodb.net/?appName=attached
    database: editer

server:
  port: 8081  # 或你喜欢的端口

# JWT 密钥（生产环境用随机强密钥，长度至少 32 位）
jwt:
  secret: your-super-secret-key-2026-change-this-to-very-long-random-string
  # noinspection SpringBootApplicationYaml
  expiration: 86400000  # 过期时间，单位 ms（这里是 24 小时）

# 日志（调试用）
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.data.mongodb: INFO  # 重点开这个看 Mongo 连接
    com.mongodb: INFO
    rj.collaborative: debug  # 开启项目包 DEBUG 日志
    org.springframework.messaging: debug  # WebSocket 消息日志
    org.springframework.web.socket: debug  # WebSocket 连接日志
