spring:
  application:
    name: real-time-collaborative-doc
  data:
    mongodb:
      uri: mongodb+srv://ranjin:${password:123456789%21}@attached.vpgh8cz.mongodb.net/?appName=attached

logging:
  level:
    # 设置根日志级别为 WARN，这样 INFO 级别的系统启动日志就不会显示
    root: warn